package com.ringforge.chord.events;

public enum EventType {
    RING_CREATED,
    NODE_JOINED,
    NODE_LEFT,
    NODE_FAILED,
    KEY_STORED,
    KEY_DELETED,
    KEY_MIGRATED,
    REPLICA_WRITTEN,
    REPLICA_PROMOTED,
    LOOKUP_COMPLETED,
    RING_REPAIRED,
    DIAGNOSTIC_REPORTED,
    BENCHMARK_COMPLETED
}
